services:
  closed-symmetry-loop:
    build:
      context: .
      dockerfile: Dockerfile
    # command: nvidia-smi
    volumes:
      - /home/domin/Documents/GitHub/closed-symmetry-loop:/tf/notebooks
      - /home/domin/Documents/Datasets/tless:/tf/notebooks/datasets/tless
      - /home/domin/Documents/Datasets/closed-symmetry-loop:/tf/notebooks/datasets/closed-symmetry-loop
    ports:
      - 8888:8888
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    container_name: robot_vision24